name: CI

on:
  pull_request:
    branches: [ develop, main ]
jobs:
  detekt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: run detekt
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: detekt
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run unit-tests
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: test

      - uses: actions/upload-artifact@v2
        name: Upload tests results
        with:
          name: unit-tests-retorts
          path: app/build/test-results/