name: detekt

on:
  pull_request:
    branches: [ develop, main ]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: run detekt
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: detekt